const mongoose = require("mongoose");

// A registered employee computer running the attendance agent.
// The agent authenticates with a random device token (only its SHA-256 hash is
// stored here) instead of the employee's password.
const deviceSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "UserAccounts",
      required: true,
    },
    userName: { type: String, default: "" },
    branchId: { type: mongoose.Schema.Types.ObjectId, ref: "Branch", default: null },

    // Stable fingerprint generated by the agent (hostname + MAC hash)
    deviceId: { type: String, required: true, unique: true, trim: true },
    hostname: { type: String, default: "", trim: true },
    platform: { type: String, default: "", trim: true },
    agentVersion: { type: String, default: "", trim: true },

    tokenHash: { type: String, default: "", select: false },

    // ACTIVE  = accepted
    // PENDING = additional device waiting for admin approval
    // REVOKED = blocked
    status: {
      type: String,
      enum: ["ACTIVE", "PENDING", "REVOKED"],
      default: "ACTIVE",
    },

    registeredAt: { type: Date, default: Date.now },
    approvedBy: { type: String, default: "" },
    approvedAt: { type: Date, default: null },
    revokedAt: { type: Date, default: null },

    lastSeenAt: { type: Date, default: null },
    lastSsid: { type: String, default: "" },
    lastBssid: { type: String, default: "" },
    lastIp: { type: String, default: "" },
  },
  { timestamps: true }
);

deviceSchema.index({ userId: 1, status: 1 });
deviceSchema.index({ tokenHash: 1 });

module.exports = mongoose.model("Device", deviceSchema);
